# Generated by Django 4.0.2 on 2022-02-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_add_initial_data_to_menu_and_dish_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='menus', to='menu.Dish'),
        ),
    ]
